(function(){
  function read(key){try{var v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch(e){return []}}
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]})}
  function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function date(v){if(!v)return '—';try{return new Date(String(v).slice(0,10)+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}catch(e){return esc(v)}}
  function state(){return window.P1&&P1.state?P1.state():read('advocateDeskData')}
  function caseClients(c,s){var ids=Array.isArray(c.clientIds)?c.clientIds.slice():[];if(!ids.length&&c.clientId)ids=[c.clientId];if(!ids.length&&c.client){var x=(s.clients||[]).find(function(v){return v.name===c.client});if(x)ids=[x.id]}return ids.map(function(id){return (s.clients||[]).find(function(x){return String(x.id)===String(id)})}).filter(Boolean)}
  function idsOf(c){var a=Array.isArray(c.clientIds)?c.clientIds.slice():[];if(!a.length&&c.clientId)a=[c.clientId];return a.filter(Boolean).map(String)}
  function explicitCaseLink(x,c){return [x.caseId,x.caseNumber,x.case,x.caseNo].some(function(v){return String(v||'').trim()===String(c.id).trim()||String(v||'').trim()===String(c.number).trim()})}
  function clientIdsOf(x){var a=Array.isArray(x.clientIds)?x.clientIds.slice():[];if(!a.length&&x.clientId)a=[x.clientId];return a.filter(Boolean).map(String)}
  function legacyMeetingMatches(m,c,s){
    if(explicitCaseLink(m,c))return true;
    var mid=clientIdsOf(m),cid=idsOf(c);if(!mid.length||!cid.length)return false;
    var overlap=mid.some(function(id){return cid.indexOf(id)!==-1});if(!overlap)return false;
    if(String(m.caseTitle||'').trim()&&String(m.caseTitle).trim().toLowerCase()===String(c.title||'').trim().toLowerCase())return true;
    if(String(m.court||'').trim()&&String(m.court).trim().toLowerCase()===String(c.court||'').trim().toLowerCase())return true;
    var clientCases=(s.cases||[]).filter(function(z){return idsOf(z).some(function(id){return mid.indexOf(id)!==-1})});
    return clientCases.length===1;
  }
  function matchesCase(x,c,s){return explicitCaseLink(x,c)||legacyMeetingMatches(x,c,s)}
  function getFinance(c){var s=state();var fees=(s.caseFees||[]).filter(function(x){return explicitCaseLink(x,c)}),pays=(s.feePayments||[]).filter(function(x){return explicitCaseLink(x,c)}),adds=(s.additionalChargeTransactions||[]).filter(function(x){return explicitCaseLink(x,c)});var agreed=fees.reduce(function(a,x){return a+Number(x.agreedFee||x.agreedFees||0)},0),feeAdditional=fees.reduce(function(a,x){return a+Number(x.additionalCharges||0)},0),received=pays.reduce(function(a,x){return a+Number(x.amount||0)},0),additional=feeAdditional+adds.reduce(function(a,x){return a+Number(x.amount||0)},0);return{agreed:agreed,received:received,additional:additional,balance:agreed+additional-received,pays:pays,adds:adds}}
  function card(title,body,extra){return '<div class="panel" style="margin-bottom:16px"><div class="panel-head"><h3>'+title+'</h3>'+(extra||'')+'</div><div class="panel-body" style="padding:14px">'+body+'</div></div>'}
  function openCaseMeeting(caseId){if(typeof window.openModal!=='function'){alert('New Meeting is loading. Please try again.');return}window.openModal('meeting');var tries=0,timer=setInterval(function(){tries++;var sel=document.getElementById('meetingCaseNumber');if(sel){var value=String(caseId),opt=Array.prototype.slice.call(sel.options).find(function(o){return String(o.value)===value});if(opt){sel.value=opt.value;sel.dispatchEvent(new Event('change',{bubbles:true}));clearInterval(timer)}}if(tries>30)clearInterval(timer)},50)}
  function open(caseNumber){var s=state(),c=(s.cases||[]).find(function(x){return String(x.number).trim().toLowerCase()===String(caseNumber).trim().toLowerCase()||String(x.id).trim().toLowerCase()===String(caseNumber).trim().toLowerCase()});if(!c){alert('Case not found.');return}var clients=caseClients(c,s),hearingRows=(s.hearings||[]).filter(function(h){return explicitCaseLink(h,c)||String(h.case||'').trim()===String(c.number).trim()}),taskRows=(s.tasks||[]).filter(function(t){return explicitCaseLink(t,c)||String(t.case||'').trim()===String(c.number).trim()}),meetingRows=(s.meetings||[]).filter(function(m){return matchesCase(m,c,s)}),discussionRows=(s.discussions||[]).filter(function(d){return matchesCase(d,c,s)}),docRows=(s.documents||[]).filter(function(d){return matchesCase(d,c,s)}),f=getFinance(c);
    var body='<div class="page-title"><div><h1>Case 360</h1><p>Complete case workspace — '+esc(c.number)+'</p></div><button class="secondary" onclick="navigate(\'cases\')">← Back to Cases</button></div>';
    body+='<div class="panel" style="margin-bottom:16px"><div class="panel-head"><h3>'+esc(c.number)+' — '+esc(c.title)+'</h3><span class="badge '+(c.status==='Active'?'green':'blue')+'">'+esc(c.status||'')+'</span></div><div class="panel-body" style="padding:14px"><div class="cards"><div class="stat"><div class="stat-top">Client</div><div class="stat-value" style="font-size:20px">'+esc(clients.map(function(x){return x.name}).join(', ')||c.client||'—')+'</div><div class="stat-foot">'+esc(c.type||'Case')+'</div></div><div class="stat"><div class="stat-top">Court</div><div class="stat-value" style="font-size:18px">'+esc(c.court||'—')+'</div><div class="stat-foot">Next hearing: '+date(c.next)+'</div></div><div class="stat"><div class="stat-top">Hearings</div><div class="stat-value">'+hearingRows.length+'</div><div class="stat-foot">Linked to this case</div></div><div class="stat"><div class="stat-top">Open Tasks</div><div class="stat-value">'+taskRows.filter(function(t){return String(t.status||'').toLowerCase()!=='completed'}).length+'</div><div class="stat-foot">Requires attention</div></div></div></div></div>';
    body+=card('Client',clients.length?clients.map(function(cl){return '<div class="list-row"><div class="list-main"><strong>'+esc(cl.name)+'</strong><small>'+esc(cl.phone||'')+(cl.email?' • '+esc(cl.email):'')+'</small></div></div>'}).join(''):'<div class="empty">No linked client.</div>','<button class="secondary" onclick="navigate(\'clients\')">Open Clients</button>');
    body+=card('Hearings',hearingRows.length?hearingRows.slice().sort(function(a,b){return String(a.date).localeCompare(String(b.date))}).map(function(h){return '<div class="list-row"><div class="date-box"><b>'+new Date(h.date+'T00:00:00').getDate()+'</b><small>'+new Date(h.date+'T00:00:00').toLocaleString('en',{month:'short'})+'</small></div><div class="list-main"><strong>'+esc(h.title||c.title)+'</strong><small>'+date(h.date)+' • '+esc(h.time||'')+' • '+esc(h.court||c.court||'')+' • '+esc(h.stage||'')+'</small></div></div>'}).join(''):'<div class="empty">No hearings linked to this case.</div>','<button class="secondary" onclick="navigate(\'hearings\')">Open Hearings</button>');
    body+=card('Discussion History',discussionRows.length?discussionRows.slice().reverse().map(function(d){return '<div class="list-row"><div class="list-main"><strong>'+esc(d.subject||d.title||'Client Discussion')+'</strong><small>'+date(d.date||d.createdAt)+' • '+esc(d.details||d.notes||d.description||'')+'</small></div></div>'}).join(''):'<div class="empty">No discussion history linked to this case yet.</div>','<button class="secondary" onclick="navigate(\'client-management\')">Open Client Management</button>');
    body+=card('Client Meetings',meetingRows.length?meetingRows.slice().sort(function(a,b){return String(a.date+a.time).localeCompare(String(b.date+b.time))}).map(function(m){return '<div class="list-row"><div class="date-box"><b>'+new Date(m.date+'T00:00:00').getDate()+'</b><small>'+new Date(m.date+'T00:00:00').toLocaleString('en',{month:'short'})+'</small></div><div class="list-main"><strong>'+esc(m.subject||'Client Meeting')+'</strong><small>'+date(m.date)+' • '+esc(m.time||'')+' • '+esc(m.mode||'')+' • '+esc(m.clientName||'')+'</small></div></div>'}).join(''):'<div class="empty">No case-linked meetings yet.</div>','<button class="secondary" onclick="openCaseMeeting('+JSON.stringify(c.id)+')">＋ New Meeting</button>');
    body+=card('Tasks',taskRows.length?taskRows.map(function(t){return '<div class="list-row"><div class="list-main"><strong>'+esc(t.title)+'</strong><small>Due: '+date(t.due)+' • '+esc(t.priority||'')+' • '+esc(t.status||'')+'</small></div></div>'}).join(''):'<div class="empty">No tasks linked to this case yet.</div>','<button class="secondary" onclick="openModal(\'task\')">＋ New Task</button>');
    body+=card('Finance','<div class="cards"><div class="stat"><div class="stat-top">Agreed Fees</div><div class="stat-value" style="font-size:20px">'+money(f.agreed)+'</div></div><div class="stat"><div class="stat-top">Additional Charges</div><div class="stat-value" style="font-size:20px">'+money(f.additional)+'</div></div><div class="stat"><div class="stat-top">Amount Received</div><div class="stat-value" style="font-size:20px">'+money(f.received)+'</div></div><div class="stat"><div class="stat-top">Outstanding</div><div class="stat-value" style="font-size:20px">'+money(f.balance)+'</div></div></div><div style="margin-top:12px">'+(f.pays.length?'<strong>Payments:</strong> '+f.pays.map(function(p){return date(p.date)+' — '+money(p.amount)}).join(' &nbsp; | &nbsp; '):'No payment history.')+'</div>'+(f.adds.length?'<div style="margin-top:8px"><strong>Additional charges:</strong> '+f.adds.map(function(a){return date(a.date)+' — '+money(a.amount)}).join(' &nbsp; | &nbsp; '):'')+'</div>','<button class="secondary" onclick="p1FeeSetup('+JSON.stringify(c.id)+')">＋ Case Fee</button> <button class="secondary" onclick="p1TransactionModal(\'payment\','+JSON.stringify(c.id)+')">＋ Payment</button> <button class="secondary" onclick="navigate(\'finance\')">Open Finance</button>');
    body+=card('Documents',docRows.length?docRows.map(function(d){return '<div class="list-row"><div class="list-main"><strong>'+esc(d.name||d.fileName||'Document')+'</strong><small>'+date(d.date||d.createdAt)+'</small></div></div>'}).join(''):'<div class="empty">No documents linked to this case yet.</div>','<button class="secondary" onclick="navigate(\'documents\')">Open Documents</button>');
    var content=document.getElementById('content');if(content){content.innerHTML=body;window.scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('.nav-item').forEach(function(b){b.classList.toggle('active',b.dataset.page==='cases')})}}
  window.openCase360=open;
  function enhanceCaseRows(){var table=document.getElementById('caseTable');if(!table)return;table.querySelectorAll('tbody tr').forEach(function(row){if(row.querySelector('[data-case360]'))return;var n=row.cells&&row.cells[0]&&row.cells[0].innerText.split('\n')[0].trim();if(!n)return;var cell=row.cells[row.cells.length-1];if(!cell)return;var b=document.createElement('button');b.className='secondary';b.setAttribute('data-case360','1');b.textContent='Case 360';b.onclick=function(){open(n)};cell.appendChild(b)})}
  function enhanceSearch(){var input=document.getElementById('globalSearch');if(!input||input.dataset.case360Bound)return;input.dataset.case360Bound='1';input.addEventListener('input',function(){setTimeout(function(){var q=input.value.trim();var s=state(),c=(s.cases||[]).find(function(x){return String(x.number||'').trim().toLowerCase()===q.toLowerCase()}),drop=document.getElementById('globalSearchResults');if(!c||!drop)return;if(drop.querySelector('[data-case360]'))return;var b=document.createElement('button');b.type='button';b.className='secondary';b.setAttribute('data-case360','1');b.style.cssText='margin:8px;width:calc(100% - 16px)';b.textContent='Open Case 360';b.onclick=function(e){e.preventDefault();e.stopPropagation();drop.style.display='none';input.value='';open(c.number)};drop.appendChild(b)},40)})}
  function boot(){enhanceSearch();enhanceCaseRows();var o=new MutationObserver(function(){enhanceSearch();enhanceCaseRows()});o.observe(document.getElementById('content')||document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();