(function(){
const K='advocateDeskData';
const BASE={cases:[{id:'CS-2026-001',number:'OS 145/2026',title:'Rahman v. State',client:'Abdul Rahman',court:'District Court, Kozhikode',next:'2026-09-08',status:'Active',type:'Civil'},{id:'CS-2026-002',number:'CC 88/2026',title:'Fathima v. Kareem',client:'Fathima P.',court:'JMFC Court II',next:'2026-09-10',status:'Pending',type:'Criminal'},{id:'CS-2026-003',number:'WP 422/2026',title:'ABC Traders v. State',client:'ABC Traders',court:'High Court of Kerala',next:'2026-09-15',status:'Active',type:'Writ'},{id:'CS-2026-004',number:'OP 71/2025',title:'Shameer v. Amina',client:'Shameer K.',court:'Family Court',next:'2026-09-18',status:'Reserved',type:'Family'}],clients:[{id:'CL-001',name:'Abdul Rahman',phone:'9876543210',email:'rahman@example.com',cases:2,status:'Active'},{id:'CL-002',name:'Fathima P.',phone:'9895001122',email:'fathima@example.com',cases:1,status:'Active'},{id:'CL-003',name:'ABC Traders',phone:'9847002211',email:'office@abctraders.example',cases:1,status:'Active'},{id:'CL-004',name:'Shameer K.',phone:'9961007788',email:'shameer@example.com',cases:1,status:'Active'}],hearings:[{date:'2026-09-08',time:'10:30 AM',case:'OS 145/2026',title:'Rahman v. State',court:'District Court, Kozhikode',stage:'Evidence'},{date:'2026-09-10',time:'11:00 AM',case:'CC 88/2026',title:'Fathima v. Kareem',court:'JMFC Court II',stage:'Arguments'},{date:'2026-09-15',time:'10:00 AM',case:'WP 422/2026',title:'ABC Traders v. State',court:'High Court of Kerala',stage:'Admission'},{date:'2026-09-18',time:'02:00 PM',case:'OP 71/2025',title:'Shameer v. Amina',court:'Family Court',stage:'Mediation'}],tasks:[{title:'Prepare counter affidavit',case:'OS 145/2026',due:'2026-09-06',priority:'High',status:'In Progress'},{title:'Collect client documents',case:'CC 88/2026',due:'2026-09-07',priority:'Medium',status:'Pending'},{title:'Review writ petition',case:'WP 422/2026',due:'2026-09-11',priority:'High',status:'Pending'}]};
window.P1={
 state(){let s={};try{s=JSON.parse(localStorage.getItem(K)||'null')}catch(e){};if(!s)s=JSON.parse(JSON.stringify(BASE));['cases','clients','hearings','tasks','discussions','meetings','financeTransactions','documents'].forEach(k=>s[k]=Array.isArray(s[k])?s[k]:[]);s.settings=Object.assign({firmName:'',advocateName:'',phone:'',email:'',whatsapp:'',barNumber:'',address:'',defaultCourt:'',timezone:'Asia/Kolkata'},s.settings||{});return s},
 save(s){localStorage.setItem(K,JSON.stringify(s))},
 esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))},
 date(v){return v?new Date(String(v).slice(0,10)+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'},
 money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})},
 btn(t,fn,p){return `<button class="${p?'primary':'secondary'}" onclick="${fn}">${this.esc(t)}</button>`},
 content(){return document.getElementById('content')},
 layout(t,s,a){return `<div class="page-title"><div><h1>${this.esc(t)}</h1><p>${this.esc(s||'')}</p></div>${a||''}</div>`},
 nav(p){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p))}
};
window.p1OpenModal=function(title,body){let m=document.getElementById('p1Modal');if(!m){m=document.createElement('div');m.id='p1Modal';m.className='modal hidden';document.body.appendChild(m)}m.innerHTML=`<div class="modal-card"><div class="modal-head"><h3>${P1.esc(title)}</h3><button onclick="p1CloseModal()">×</button></div>${body}</div>`;m.classList.remove('hidden');document.body.classList.add('p1-modal-open')};
window.p1CloseModal=function(){document.getElementById('p1Modal')?.classList.add('hidden');document.body.classList.remove('p1-modal-open')};
function boot(){document.addEventListener('click',e=>{const n=e.target.closest?.('.nav-item[data-page]');if(!n)return;const p=n.dataset.page;if(['finance','reports','settings','documents','calendar'].includes(p)){e.preventDefault();e.stopImmediatePropagation();P1.nav(p);document.body.classList.remove('menu-open');document.querySelector('.sidebar')?.classList.remove('open');document.getElementById('mobileOverlay')?.classList.remove('open');if(p==='finance')window.p1Finance();if(p==='reports')window.p1Reports();if(p==='settings')window.p1Settings();if(p==='documents')window.p1Documents();if(p==='calendar')window.p1Calendar()}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();